[package]
name = "passwordmanager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
serde_json = { version = "1.0" }
hex = "0.4"
openssl = "0.10.52"


